### ISSUE TITLE
[Enhancement] Make the map bigger on smaller screens

### ISSUE THREAD

**Issue by Preciousstowers** [info442-aut21/c-team#105]
Using the map on a phone is hard because the map is too small. This is necessary because in order to click and drag locations on the map, having a large space or having the map on a new page would be easier.

**Comment by julianedelossantos** [comment]
- this issue was able to be reproduced on iPhone 8+ Safari iOS15
- the requirement of the map picture will be removed as it serves a small purpose to our overarching mission, but this map is also overwhelmingly large on mobile screens
- instead of the picture, we will address the implementation of the map under this section through #90 and #91
