### ISSUE TITLE
[Major] Did not register an account but still logged in automatically to "testuser"

### ISSUE THREAD

**Issue by Skylitmoon** [info442-aut21/c-team#110]
This was tested on MacOS Monterey and Google Chrome Version 96.0.4664.45.

1. Skip registration process
2. Navigate to Profile from the navbar
3. Click View my profile
4. Click Sign Out
5. Click view my profile

Even when trying to Sign Out, I keep getting logged in to the testuser account.

**Comment by julianedelossantos** [comment]
-this issue was reproduced on Windows 11 Google Chrome Version 96.0.4664.45
-proper user authentication was not implemented in phase 6, so all pages were available to the user without them having to log in
-we will address this issue by first changing the profile dropdown options to default to just "log in" and then making the "view my profile" and "log out" options available and functional once the user is logged in during that session
-the profile tab will return the actual user's username and college instead of our placeholder ones by calling that information from the database
