### ISSUE TITLE
[Enhancement] Categories for Feed 

### ISSUE THREAD

**Issue by Vivianngu3** [info442-aut21/c-team#112]
This is a stretch but it would be convenient for users to be able to have specific forum tabs/most used tags filters(checkboxes) to cater to their needs/queries instead of having to think or search specifically on their own. It will give a bit more help/guidance to what they can look for.

**Comment by julianedelossantos** [comment]
-since the post possibilities are endless, we aren't sure what kind of benefit having a checkbox would serve for our users
-there are thousands of colleges to choose from, for example, which means it would be easier to just type in that college and search posts through that query instead of finding the college to check and filter
