### ISSUE TITLE
[Minor] Navbar does not remain persistent when scrolling

### ISSUE THREAD

**Issue by aramos10-1863966** [info442-aut21/c-team#117]
Description: When I was observing the feed and scrolled down the page of content to see the other posts, I noticed that the navbar didn't stay at the top of my screen, it left the page. Navigation on a site is important, especially in an app that expects many posts to be created and scrolled through. Users being able to quickly navigate between their feed and resources will improve the experience and functionality of the web app.

Expectation: Navbar to remain persistent at the top of the screen

Environment: Microsoft Edge Version 96.0.1054.29

**Comment by julianedelossantos** [comment]
-it was an initial design choice to not have the navigation bar fixed; however, we agree with your point that on the infinitely scrollable pages such as home and user profile, it would be a hassle to scroll all the way up
-we plan to edit the header elements to be fixed at the top of the page through css

**Comment by julianedelossantos** [comment]
We recognize that solutions that have been recommended to us include a CSS fix to add top padding to the body of the page in order to avoid the issue where the fixed position of the navbar covers some of the page content (most notably the title). What happens when doing so, however, is that a large white bar presents itself in mobile view between the page content and navbar, which conflicts with our responsive design. In order to keep the responsive design, we are choosing to leave the navbar unfixed. With more time, we would look into an enhancement in which a button would appear when scrolling down the page that brings the user to the top of the page.
