### ISSUE TITLE
[Minor] Signing in with an account that doesn't exist

### ISSUE THREAD

**Issue by judysdesign** [info442-aut21/c-team#144]
macOS Big Sur 
Version 11.6
Chrome Version  96.0.4664.55

Description: When signing in with an account that doesn't exist, there isn't a message telling the user that the account hasn't been created.

Expected: Should get a message saying that account doesn't exist. Prompts the user to create an account 
Actual: Password field is just cleared.

**Comment by julianedelossantos** [comment]
The generic error message "Incorrect username or password" that has just recently been added also includes that of the user's input of a credential that does not match in our database. By design, we are minimizing the sharing of too much information to users as those with malicious intent could attempt to sign up with an email that is not theirs if they know that account has not been registered given the prompt message you are suggesting. The user will only know an account is available through the sign-up page if their credentials do not get rejected through a "duplicate" error there.

**Comment by cherimarie** [comment]
This is a good design decision, @julianedelossantos ! Limiting information in error messages is an important security step.
