### ISSUE TITLE
[Major] Unable to create multiple new posts on feed

### ISSUE THREAD

**Issue by victoriathegr8** [info442-aut21/c-team#97]
On the home/feed page, when clicking the add button in the bottom right corner and making a new post. After making one post, the second post (and all posts after that) will just replace the text content of the form. No new posts are appended to the end of the page.
Chrome v96.0.4664.45 on Windows 10
1. Navigate to home/feed page
2. Click on add button
3. Insert "test 1" into content input box
4. Press post
5. Click on add button again
6. Insert "test 2" into content input box
7. Press post
8. View last posts on the page
Expected result: see multiple appended posts at the bottom of the page
Actual result: see only one new post, with content of most recent added post only

**Comment by julianedelossantos** [comment]
-this issue was able to be reproduced on Windows 11 Chrome Browser. The expected result is actually to see the post at the top of the page after it is posted (sorted by most recent by default)
-The functionality of the post feature was not complete during phase 6, but we will work on creating new post cards for each submission first instead of content being linked to the same card
