### ISSUE TITLE
[Minor] I don't understand the purpose of the star icon 

### ISSUE THREAD

**Issue by Sneha-8** [info442-aut21/c-team#98]
Description: I don't understand the purpose behind the star icon on the feed, if it is for favoriting, you can probably add a favorites page, or if it is for liking the post maybe add a number of likes it got to be more indicative of the function.
Tested on Chrome Version 96.0.4664.55 (Official Build) on MacOs Catalina.

**Comment by Jemuelle4** [comment]
Additional comments: It looks like it appears on the saved section in the user's profile, but it doesn't seem to update properly with testuser logged in. 

Enhancement Request: Favoriting posts does not seem too relevant for the application. What does the user do with the favorite post? Can it be changed to a "like" or "love" feature instead?

**Comment by julianedelossantos** [comment]
-the functionality was not complete during phase 6 and this issue was able to be reproduced on Windows 11 Chrome Browser v96.0.4664.55
-when the star icon is filled in, that specific post should be saved as part of the user object of the user that is signed in
-it should then be able to be viewed under the "Saved tab" for the user profile
-clicking the start icon a second time, either on the home feed page or the user profile page will remove it from the user object and thus remove it from view under the user's "saved" posts
