### ISSUE TITLE
[Enhencement Minor] On a smaller screen, the arrangement of the navlinks and add new post function.

### ISSUE THREAD

**Issue by ychen023** [info442-aut21/c-team#99]
<img width="1439" alt="Screen Shot 2021-11-22 at 9 38 26 AM" src="https://user-images.githubusercontent.com/59670580/142908993-e7227aca-2ab4-47e9-8d1c-6bd25e77a7d1.png">
On a smaller screen, the arrangement of the navlinks and add new post function, should find a better place for add new post. Also the nav link should not be like this, you can make like a hambuger drop down menu instead. 

environment it was encountered in: Iphone X
steps to reproduce: Home page on iphone X size screen. 
expected result: The nav link is formated correctly. 
actual result: The nav link is squeezed as the page width gets smaller.

**Comment by sershon** [comment]
Additional info:

On a Samsung Galaxy S21 running Android 12 on Google Chrome, the content spills outside of the intended space. The navbar is repsonsive, but not some of the content like the video. I would expect that the video is constrained to the width of my phone screen as well. This is what it looks like when I zoom out
![jpeg](https://user-images.githubusercontent.com/72484672/142910220-d0ea0b9a-4c70-4993-abf2-6b0dea585eb6.jpeg)
.

**Comment by julianedelossantos** [comment]
-the issue was able to be reproduced on iPhone 8+ Safari iOS15
-we did not complete our responsive design in phase 6
-our first step to solve this view on various mobile devices is to fit all of the content within the boundaries of the full html page
-we would then edit the css of certain elements such as the video and the navigation tabs to be smaller in text size through media queries and consistent with the view on desktop browsers

**Comment by julianedelossantos** [comment]
We were able to fix the content spilling over the other page elements
